stages:
  - build
  - destroy

deploy-nginx:
  stage: build
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  variables:
    KUBE_CONTEXT: pierretenrique/kubernetes-test:k3s-agent
  script:
    - kubectl config use-context "$KUBE_CONTEXT"
    - kubectl apply -f k8s/nginx.yaml --validate=false
    - kubectl get pods

destroy-nginx:
  stage: destroy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  variables:
    KUBE_CONTEXT: pierretenrique/kubernetes-test:k3s-agent
  script:
    - kubectl config use-context "$KUBE_CONTEXT"
    - kubectl delete -f k8s/nginx.yaml
  when: manual