stages:
  - build
  - setup
  - expose
  - verification
  - pdf

deploy-nginx:
  stage: build
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  variables:
    KUBE_CONTEXT: pierretenrique/kubernetes-test:k3s-agent
  script:
    - kubectl config use-context "$KUBE_CONTEXT"
    - kubectl apply -f k8s/nginx.yaml --validate=false
    - kubectl get pods

setup-nginx:
  stage: setup
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  variables:
    KUBE_CONTEXT: pierretenrique/kubernetes-test:k3s-agent
  script:
    - echo -e "disable:\n  - traefik" | sudo tee -a /etc/rancher/k3s/config.yaml
    - sudo systemctl restart k3s
    - cat /etc/rancher/k3s/config.yaml
    - kubectl config use-context "$KUBE_CONTEXT"
    - kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml
    - helm install ngf oci://ghcr.io/nginxinc/charts/nginx-gateway-fabric --create-namespace -n nginx-gateway

expose-nginx:
  stage: expose
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  variables:
    KUBE_CONTEXT: pierretenrique/kubernetes-test:k3s-agent
  script:
    - kubectl config use-context "$KUBE_CONTEXT"
    - kubectl apply -f k8s/gateway.yaml
    - kubectl expose deployment nginx-ci --name ci-svc --port 80 --target-port 80
    - kubectl get gateway
    - kubectl get httproute

verification:
  stage: verification
  image: curlimages/curl:latest
  script:
    - NODE_IP=192.168.1.48
    - NODE_PORT=31325
    - echo "Testing Gateway API routing..."
    - curl -f -H "Host: deployci.com" http://$NODE_IP:$NODE_PORT
    - echo "Test reussi !"

pdf:
  stage: pdf
  script:
    - echo "generating pdf..."
  artifacts:
    paths:
      - my_goal.pdf