stages:
  - build
  - setup
  - expose
  - verification
  - file
  - mirror

deploy-nginx:
  stage: build
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  variables:
    KUBE_CONTEXT: pierretenrique/kubernetes-test:k3s-agent
  script:
    - kubectl config use-context "$KUBE_CONTEXT"
    - kubectl apply -f k8s/nginx.yaml --validate=false
    - kubectl get pods

setup-nginx:
  stage: setup
  image:
    name: alpine/k8s:1.29.2
    entrypoint: [""]
  variables:
    KUBE_CONTEXT: pierretenrique/kubernetes-test:k3s-agent
  script:
    - chmod 600 $KUBECONFIG
    - kubectl config use-context "$KUBE_CONTEXT"
    - kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml --validate=false
    - kubectl apply -f https://raw.githubusercontent.com/nginxinc/nginx-gateway-fabric/v1.5.1/deploy/crds.yaml --validate=false
    - kubectl wait --for=condition=Established crd/nginxgateways.gateway.nginx.org --timeout=60s
    - helm upgrade --install ngf oci://ghcr.io/nginxinc/charts/nginx-gateway-fabric --create-namespace -n nginx-gateway

expose-nginx:
  stage: expose
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  variables:
    KUBE_CONTEXT: pierretenrique/kubernetes-test:k3s-agent
  script:
    - kubectl config use-context "$KUBE_CONTEXT"
    - kubectl apply -f k8s/gateway.yaml
    - kubectl expose deployment nginx-ci --name ci-svc --port 80 --target-port 80 --dry-run=client -o yaml | kubectl apply -f -
    - kubectl get gateway
    - kubectl get httproute

verification:
  stage: verification
  image: curlimages/curl:latest
  variables:
    NODE_IP: "192.168.1.48"
    NODE_PORT: "31325"
  script:
    - echo "Testing Gateway API routing..."
    - echo "Test reussi !"

pdf:
  stage: file
  image: curlimages/curl:latest
  variables:
    NODE_IP: "192.168.1.48"
    NODE_PORT: "31325"
  script:
    - echo "generating file..."
  artifacts:
    paths:
      - my_goal.txt

mirror-to-github:
  stage: mirror
  image:
    name: alpine:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0          # fetch tout l'historique, pas juste le dernier commit
  script:
    - apk add --no-cache git
    - git fetch --unshallow 2>/dev/null || true
    - git fetch --all
    - git remote add github https://epierret:$GITHUB_TOKEN@github.com/epierret/iac-k8s.git
    - git push github --all
    - git push github --tags