apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ci
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-stub-status
              mountPath: /etc/nginx/conf.d/stub_status.conf
              subPath: stub_status.conf
      volumes:
        - name: nginx-stub-status
          configMap:
            name: nginx-stub-status
